run:
  timeout: 10m
  go: '1.21.0'
linters:
  enable-all: true
  disable:
    # deprecated
    - ifshort
    - nosnakecase
    - deadcode
    - interfacer
    - structcheck
    - maligned
    - varcheck
    - scopelint
    - exhaustivestruct
    - golint

    # too annoy
    - depguard
    - stylecheck
    - exhaustruct
    - wrapcheck
    - gci
    - wsl
    - gomnd
    - nlreturn
    - godox
    - varnamelen
    - funlen
    - cyclop

