name: Lint runner
on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
